config/routes.rb
Rails.application.routes.draw do
  get 'publishers/new'

  get 'publishers/create'

  get 'publishers/update'

  get 'publishers/edit'

  get 'publishers/destroy'

  get 'publishers/index'

  get 'publishers/show'

  get 'authors/new'

  get 'authors/create'

  get 'authors/update'

  get 'authors/edit'

  get 'authors/destroy'

  get 'authors/index'

  get 'authors/show'

  get 'categories/new'

  get 'categories/create'

  get 'categories/update'

  get 'categories/edit'

  get 'categories/destroy'

  get 'categories/index'

  get 'categories/show'

  get 'books/new'

  get 'books/create'

  get 'books/update'

  get 'books/edit'

  get 'books/destroy'

  get 'books/index'

  get 'books/show'

  get 'about/index'

  get 'about' => 'about#index'

  root 'books#index'

  resources :books
  resources :authors
  resources :categories
  resources :publishers

end

app/models/author.rb
class Author < ActiveRecord::Base
	has_many :books
	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/book.rb
class Book < ActiveRecord::Base
	 belongs_to :category
	 belongs_to :author
	 belongs_to :publisher
end
 

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books
	validates :name, presence: true, length: {minimum: 3}
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books
	validates :name, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  	@page_title = 'About us';
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @page_title = 'Add new Author'
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save

    redirect_to authors_path
  end

  def update
    @author = Author.find(params[author_params])
    @author.update
    flash[:notice] = "Author Updated Successfully"
    redirect_to authors_path
  end

  def edit
    @author = Author.find(params[:id])
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    flash[:alert] = "Author Removed"
    redirect_to authors_path
  end

  def index
    @author = Author.all
  end

  
  private
    def author_params
    params.require(:author).permit!
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @page_title = 'Add Book'
    @book = Book.new
    @category = Category.new
    @author = Author.new
    @publisher = Publisher.new

  end

  def create
    @book = Book.new(book_params)
    @book.save
    flash[:notice] = "Book has been successfully Created"
    redirect_to books_path

  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    flash[:notice] = "Book has been successfully Updated"
    redirect_to books_path

  end

  def edit
    @book = Book.find(params[:id])

  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    flash[:notice] = "Book has been successfully Deleted"
    redirect_to books_path

  end

  def index
    @books = Book.all
    @categories = Category.all
  end

  def show
    @book = Book.find(params[:id])
    @categories = Category.all
  end

private
  def book_params
  params.require(:book).permit!
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @page_title = 'Add New Category'
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if
     @category.save
     flash[:notice] = "Category Created Successfully"
     redirect_to categories_path
    else
      render 'new'
    end
  end


  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    flash[:notice] = "Category Updated"
    redirect_to categories_path
  end

  def edit
    @category = Category.find(params[:id])

  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = "Category Removed"
    redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @categories = Category.all
    @books = @category.books 
  end
end

private
  def category_params
  params.require(:category).permit!
  end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def new
    @page_title = 'Add new Publisher'
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(publisher_params)
      if
     @publisher.save
     flash[:notice] = "Publisher Created Successfully"
     redirect_to publishers_path
      else
      render 'new'
      end
    
  end

  def update
    @publisher = Publisher.find(prams[publisher_params])
    @publisher.update
    flash[:notice] = "Publisher Updated"
    redirect_to publishers_path
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    flash[:alert] = "Publisher Removed"
    redirect_to 'publishers_path'
  end

  def index
    @publisher = Publisher.all
  end

  def show
  end

private
  def publisher_params
  params.require(:publisher).permit!
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/about/index.html.erb
<h1> <%= @page_title %> </h1>
<p>This is sample bookstore application</p>

app/views/authors/create.html.erb
<h1>Authors#create</h1>
<p>Find me in app/views/authors/create.html.erb</p>

app/views/authors/destroy.html.erb
<h1>Authors#destroy</h1>
<p>Find me in app/views/authors/destroy.html.erb</p>

app/views/authors/edit.html.erb
<h2> Edit Author </h2>

<%= form_for @author do |f| %>
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
	<% end %>

	<div class="form-group">
	<%= f.label :first_name %><br/>
	<%= f.text_field :first_name, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :last_name %><br/>
	<%= f.text_field :last_name, class:'form-control' %><br/>
	</div>


	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/index.html.erb
<h2>Author</h2>

<table>
	<tr>
		<th>Authors Name</th>
		<th>Actions</th>
	</tr>
<br/>
	<% @author.each do |author| %>
		<tr>
			<td><%= author.first_name %> <%= author.last_name %></td>
			<td><%= link_to 'Edit', edit_author_path(author.id) %> | <%= link_to 'Delete', author_path(author), method: :delete, data: {confirm: "Are You Sure?"} %> </td>
		</tr>
	<% end %>
</table>

app/views/authors/new.html.erb
<h2> Add New Author </h2>

<%= form_for @author do |f| %>
	<% if @author.errors.any? %>
		<% @author.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
	<% end %>

	<div class="form-group">
	<%= f.label :first_name %><br/>
	<%= f.text_field :first_name, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :last_name %><br/>
	<%= f.text_field :last_name, class:'form-control' %><br/>
	</div>


	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", authors_path, class:'btn btn-default' %>

<% end %>

app/views/authors/show.html.erb
<h1>Authors#show</h1>
<p>Find me in app/views/authors/show.html.erb</p>

app/views/authors/update.html.erb
<h1>Authors#update</h1>
<p>Find me in app/views/authors/update.html.erb</p>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h2> Edit Book </h2>

<%= form_for @book do |f| %>
	<div class="form-group">
	<%= f.label :title %><br/>
	<%= f.text_field :title, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :isbn %><br/>
	<%= f.text_field :isbn, class:'form-control' %><br/>
	</div>
	<div class="form-group">
	<%= f.label :category %><br/>
	<%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %> <br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :author %><br/>
	<%= f.select :author_id, Author.all.collect{|x| [x.first_name + " " + x.last_name, x.id]},{:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :publisher %><br/>
	<%= f.select :publisher_id, Publisher.all.collect{|x| [x.name, x.id]},{:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :format %><br/>
	<%= f.text_field :format, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :year %><br/>
	<%= f.text_field :year, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :coverpath %><br/>
	<%= f.text_field :coverpath, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :description %><br/>
	<%= f.text_area :description, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :pages %><br/>
	<%= f.number_field :pages, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :price %><br/>
	<%= f.text_field :price, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :buy %><br/>
	<%= f.text_field :buy, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", books_path, class:'btn btn-default' %>


<% end %>

app/views/books/index.html.erb
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-sm-3">
				<h3> <%= book.title %> </h3>
				<%= image_tag(book.coverpath) %>
				<%= link_to 'Read More', book_path(book), class: 'btn btn-primary' %>
				</div>
			<% end %> 
		</div>
	<% end %>
</div>

app/views/books/new.html.erb
<h2> Add new Book </h2>

<%= form_for @book do |f| %>
	<div class="form-group">
	<%= f.label :title %><br/>
	<%= f.text_field :title, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :isbn %><br/>
	<%= f.text_field :isbn, class:'form-control' %><br/>
	</div>
	<div class="form-group">
	<%= f.label :category %><br/>
	<%= f.select :category_id, Category.all.collect{|x| [x.name, x.id]}, {:include_blank => 'Select One'}, class:'form-control' %> <br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :author %><br/>
	<%= f.select :author_id, Author.all.collect{|x| [x.first_name + " " + x.last_name, x.id]},{:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :publisher %><br/>
	<%= f.select :publisher_id, Publisher.all.collect{|x| [x.name, x.id]},{:include_blank => 'Select One'}, class:'form-control' %><br/><br/>
	</div>

	<div class="form-group">
	<%= f.label :format %><br/>
	<%= f.text_field :format, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :year %><br/>
	<%= f.text_field :year, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :coverpath %><br/>
	<%= f.text_field :coverpath, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :description %><br/>
	<%= f.text_area :description, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :pages %><br/>
	<%= f.number_field :pages, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :price %><br/>
	<%= f.text_field :price, class:'form-control' %><br/>
	</div>

	<div class="form-group">
	<%= f.label :buy %><br/>
	<%= f.text_field :buy, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", books_path, class:'btn btn-default' %>


<% end %>

app/views/books/show.html.erb
<div id="books-show">
	<h2> <%= @book.title %></h2>
	<div class="books-show-left">
		<%= image_tag(@book.coverpath ) %>		
	</div>

	<div class="book-show-right">
	<h3>Book Info:</h3>
	<ul>
		<li><strong>Categoty: </strong> <%= @book.category.name %></li>
		<li><strong>Author:</strong><%= @book.author.first_name %> <%= @book.author.last_name %></li>
		<li><strong>Publisher:</strong><%= @book.publisher.name %></li>
		<li><strong>Year:</strong><%= @book.year %></li>
		<li><strong>ISBN:</strong><%= @book.isbn %></li>
		<li><strong>Format:</strong><%= @book.format %></li>
		<li><strong>Pages:</strong><%= @book.pages %> </li>
	</ul>
	<%= link_to "Buy for "+@book.price, @book.buy, class:'btn btn-success', target:'_blank' %>
	</div>
	<div class="clearfix"></div>
	<h4>Description</h4>
		<p><%= @book.description %></p>

		<h3>Admin Functions</h3>
		<%= link_to 'Edit', edit_book_path(@book.id) %> | <%= link_to 'Delete', book_path(@book), method: :delete, data: {confirm: "Are you sure?"} %>

	</div>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2> Edit Category </h2>

<%= form_for @category do |f| %>

	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
	<% end %>
	<div class="form-group">
	<%= f.label :name %><br/>
	<%= f.text_field :name, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<table>
	<tr>
		<th>Category Name</th>
		<th>Actions</th>
	</tr>
<br/>
	<% @categories.each do |category| %>
		<tr>
			<td><%= category.name %></td>
			<td><%= link_to 'Edit', edit_category_path(category.id) %> | <%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: "Are You Sure?"} %> </td>
		</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h2> Add New Category </h2>

<%= form_for @category do |f| %>

	<% if @category.errors.any? %>
		<% @category.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
	<% end %>
	<div class="form-group">
	<%= f.label :name %><br/>
	<%= f.text_field :name, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", categories_path, class:'btn btn-default' %>

<% end %>

app/views/categories/show.html.erb
<h2><%= @category.name %> </h2>
<div id="books-index">
	<% @books.each_slice(4) do |book| %>
		<div class="row">
			<% book.each do |book| %>
				<div class="col-md-3 col-sm-3">
				<h3> <%= book.title %> </h3>
				<%= image_tag(book.coverpath) %>
				<%= link_to 'Read More', book_path(book), class: 'btn btn-primary' %>
				</div>
			<% end %> 
		</div>
	<% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title ? @page_title : 'Welcome' %> | The BookStore </title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="<%= params[:controller] == 'books' ? 'active' : '' %>"><%= link_to 'Home', root_path %> </li>

            <li class="<%= params[:controller] == 'about' ? 'active ' : '' %>" ><%= link_to 'About', about_path %></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add New <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to 'Book', new_book_path %></li>
              <li><%= link_to 'Category', new_category_path %></li>
              <li><%= link_to 'Author', new_author_path %></li>
              <li><%= link_to 'Publisher', new_publisher_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Manage <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to 'Category', categories_path %></li>
              <li><%= link_to 'Author', authors_path %></li>
              <li><%= link_to 'Publisher', publishers_path %></li>
          </ul>
        </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <header>
      
      <div class="container">
        <h1> The BookStore <small> <%= @page_title ? @page_title : 'Welcome' %> </small> </h1>
    </header>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8">

          <% if flash[:notice] %>
            <div class="alert alert-success"> <%= flash[:notice] %></div>
          <% end %>
          <% if flash[:alert] %>
            <div class="alert alert-danger"> <%= flash[:alert] %></div>
          <% end %>
            <%= yield %> 
          </div>
          <div class="col-md-4">
           <%= render 'layouts/partials/sidebar' %> 
        </div>
      </div>
    </div>    
    </section>

    <footer>
      <div class="container">
        <p> Copyright %copy: 2016, All rights Reserved </p>

    </footer>

</body>
</html>

app/views/layouts/partials/_sidebar.html.erb
<% if params[:controller] == 'about' %>
<div class="well">
	<h3>Location Info </h3>
	<ul>
		</li>"The Vbook Store" </li>
		</li> House no: 1-76/1,</li>
		</li> Hydershakote</li>
		</li> Rajendra Nagar</li>
		</li> R R Dist, Hyd</li>
		</li>Telengana, India </li>
	</ul>
</div>
<% end %>

<% if params[:controller] == 'books' && params[:action] == 'index' || params[:action] == 'show' %>
	<div class="list-group">
	<% @categories.each do |category| %>
		<%= link_to category.name, 
			category_path(category.id),
		 	class:"list-group-item" %>
		<% end %>
	</div>
<% end %>

app/views/publishers/create.html.erb
<h1>Publishers#create</h1>
<p>Find me in app/views/publishers/create.html.erb</p>

app/views/publishers/destroy.html.erb
<h1>Publishers#destroy</h1>
<p>Find me in app/views/publishers/destroy.html.erb</p>

app/views/publishers/edit.html.erb
<h2> Edit Publisher </h2>

<%= form_for @publisher do |f| %>

<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
<% end %>
	<div class="form-group">
	<%= f.label :name %><br/>
	<%= f.text_field :name, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", publishers_path, class:'btn btn-default' %>

<% end %>

app/views/publishers/index.html.erb
<h2>Publishers</h2>

<table>
	<tr>
		<th>Publisher Name</th>
		<th>Actions</th>
	</tr>
<br/>
	<% @publisher.each do |publisher| %>
		<tr>
			<td><%= publisher.name %> </td>
			<td><%= link_to 'Edit', edit_publisher_path(publisher.id) %> | <%= link_to 'Delete', publisher_path(publisher), method: :delete, data: {confirm: "Are You Sure?"} %> </td>
		</tr>
	<% end %>
</table>

app/views/publishers/new.html.erb
<h2> Add New Publisher </h2>

<%= form_for @publisher do |f| %>

<% if @publisher.errors.any? %>
		<% @publisher.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"> <%= msg %></div>
		<% end %>	
<% end %>
	<div class="form-group">
	<%= f.label :name %><br/>
	<%= f.text_field :name, class:'form-control' %><br/>
	</div>

	<%= f.submit "Submit", class:'btn btn-primary' %>
	<%= link_to "Cancel", publishers_path, class:'btn btn-default' %>

<% end %>

app/views/publishers/show.html.erb
<h1>Publishers#show</h1>
<p>Find me in app/views/publishers/show.html.erb</p>

app/views/publishers/update.html.erb
<h1>Publishers#update</h1>
<p>Find me in app/views/publishers/update.html.erb</p>